version: '3'
services:
  geolocation_api:
    build: 
      context: .
      dockerfile: platform/Dockerfile
    depends_on:
      - postgres
    ports:
      - "4000:4000"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
     - "5432:5432"