version: '3'
services:
  geolocation_api:
    build: 
      context: .
      dockerfile: platform/dev.Dockerfile
    environment:
      DB_URL: ecto://postgres:postgres@postgres/postgres
      PORT: 4000
      HOST: localhost
    depends_on:
      - postgres
    ports:
      - "4000:4000"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
     - "5432:5432"